# Generated by Django 4.2 on 2023-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='price_usd',
            field=models.FloatField(),
        ),
    ]




