# Generated by Django 4.2 on 2023-05-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0003_auto_20230503_1545'),
    ]

    operations = [
    ]
